### ISSUE TITLE
Recipe app: Kanban board setup

### ISSUE THREAD

**Issue by omarbabou** [omarbabou/recipe-app#12]
In this issue, we have set up a Kanban board. We are two on the team.
Omar is Student A and Bernard is Student B.
This is the link to the project: https://github.com/users/omarbabou/projects/7

**Comment by julie-ify** [comment]
Hi @omarbabou and @benardop,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Your link should lead to your Kanban board, not repo. Kindly fix that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Reem-lab** [comment]
# Hi Team, 👋🏻👋🏻 

## Note for the next reviewer: My review won't take into conideration so kindly review this as a first review because I calimed the PR at the same time with another reviewer so it is disappeared when I tried to submit the form to approve it 🙏🏻



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- Great working on set up the kanban ✅
- Great on assigning the tasks between you ✅


## Optional suggestions
- [ OPTIONAL ] I suggest to make the styles card pair-programming since it is assigned to student A and he already has cards equal to student B so you can make the last card pair-programming ✅✨💯
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 
- Tasks distributed equally ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [x] Kindly provide `points` for this task 
![image](https://user-images.githubusercontent.com/24703171/208919980-92f44fa9-9bfa-42f8-bf26-6939e0d3f6ba.png)
as per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#:~:text=Has%20the%20number%20of%20points%20in%20the%20%5BXpt%5D%20prefix).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @omarbabou, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to start working on it :shipit: 
Congratulations! 🎉 

# Highlights:
- All requirements completed

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
